#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set up virtualenv environment
export WORKON_HOME=${HOME}/.virtualenvs
export PROJECT_HOME=${HOME}/Projects
export VIRTUALENVWRAPPER_VIRUTALENV_ARGS='--no-site-packages'
export VIRTUALENVWRAPPER_PYTHON=/opt/homebrew/opt/python@3.11/libexec/bin/python
